# Generated by Django 5.0.4 on 2024-07-20 13:30

import django.core.validators
import main_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Enter a valid email address'}, max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, validators=[main_app.validators.ValidateName('Name can only contain letters and spaces')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+359\\d{9}$', message="Phone number must start with '+359' followed by 9 digits")]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='website_url',
            field=models.URLField(error_messages={'invalid': 'Enter a valid URL'}),
        ),
    ]
