# Generated by Django 5.0.4 on 2024-07-20 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_book_movie_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(6, message='ISBN must be at least 6 characters long')]),
        ),
    ]
