# Generated by Django 5.0.4 on 2024-06-23 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 6, 24), null=True, verbose_name='Start Date'),
        ),
    ]
