# Generated by Django 5.0.4 on 2024-06-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
