# Generated by Django 5.0.4 on 2024-06-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_smartphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10), # type: ignore
        ),
    ]
