# Generated by Django 5.0.4 on 2024-06-27 22:42

from django.db import migrations

def new_price(apps, schema_editor):
    phone_model = apps.get_model('main_app', 'Smartphone')
    phones = phone_model.objects.all()
    
    for phone in phones:
        phone.price = len(phone.brand)*120
    
    phone_model.objects.bulk_update(phones, ['price'])

def old_price(apps, schema_editor):
    phone_model = apps.get_model('main_app', 'Smartphone')
    phones = phone_model.objects.all()
    
    for phone in phones:
        phone.price = phone_model._meta.get_field('price').default
    
    phone_model.objects.bulk_update(phones, ['price'])
    
def new_category(apps, schema_editor):
    phone_model = apps.get_model('main_app', 'Smartphone')
    phones = phone_model.objects.all()
    
    for phone in phones:
        phone.category = 'Expensive' if phone.price >= 750 else 'Cheap'
    


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_smartphone_price'),
    ]

    operations = [
        migrations.RunPython(new_price, old_price),
    ]
