# Generated by Django 5.0.4 on 2024-07-17 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_veterinarian_zookeeper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zookeeper',
            old_name='speciality',
            new_name='specialty',
        ),
    ]
