# Generated by Django 5.0.4 on 2024-06-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
